[project]
name = "mokai"
cpp_version = "c++23"
include_dirs = ["src", "tests"]

[target.MOKAI]
type = "static_library"
sources = [
    "src/config/**/*.cpp", 
    "src/graph/**/*.cpp", 
    "src/utils/**/*.cpp",
    "src/cli/**/*.cpp",
    "src/templates/**/*.cpp",
    "src/core/**/*.cpp",
]

[target.mokai]
type = "executable"
sources = ["src/entry.cpp"]
depends_on = ["MOKAI"]
flags = [
    "-fno-exceptions",
    "-fno-rtti"
]

[target.mokai_tests]
type = "executable"
sources = [
    "src/tests/conditions.cpp",
    "src/tests/extraction.cpp",
    "src/tests/build.cpp",
    "src/tests/test_parser.cpp",
    "src/tests/test_templates.cpp"
]
depends_on = ["MOKAI"]

