#pragma once

#include "graph/types.hpp"
#include "log/log.h"
#include <memory>
#include <string>
#include <unordered_set>
#include <vector>

namespace mokai {

// Forward declaration to break circular dependency with cli.hpp
struct GlobalOptions;

class Graph {
public:
  /**
   * @brief Constructs the dependency graph and initializes the flat target
   * maps.
   * @param rootManifest The root project configuration topology tree.
   * @param options Parsed CLI options holding verbosity, job count, profile
   * type, and target filters.
   */
  Graph(std::shared_ptr<ProjectManifest> rootManifest,
        const GlobalOptions &options)
      : m_root_manifest(rootManifest), m_options(options) {
    // flattens dependency manifest
    m_allTargets = flattenManifestTree(rootManifest, "root");
    m_edges = buildEdges();
  }

  void executeHooks(const std::shared_ptr<ProjectManifest> &manifest,
                    HookTrigger trigger, const std::string &target_name);

  bool
  evaluateConditionExpression(const std::string &condition,
                              const Target &target,
                              const std::shared_ptr<ProjectManifest> &manifest);

  std::vector<std::string>
  getTransitiveDependencies(const std::string &qualified_name);

  bool
  evaluateAdvancedCondition(const std::string &cond, const Target &target,
                            const std::shared_ptr<ProjectManifest> &manifest);

  bool evaluateCond(const std::string &cond_expr);

  /**
   * @brief Executes the full compilation and link orchestration sequence in
   * topological order.
   * @param build_order The validated list of qualified targets produced by
   * computeBuildOrder().
   * @return True if the entire project tree compiled and linked flawlessly;
   * false on break.
   */
  bool BuildAllTree(const std::vector<std::string> &build_order);

  /**
   * @brief Performs a topological sort on the dependency graph using a
   * post-order DFS. Detects cyclic dependencies and aborts with a descriptive
   * trace if found.
   * @param edges The fully resolved edge list generated by buildEdges().
   * @return A list of qualified target names sorted dependencies-first, or an
   * empty vector if a cycle forces an abort.
   */
  std::vector<std::string>
  computeBuildOrder(const std::vector<GraphEdge> &edges);

  std::vector<GraphEdge> getEdges() { return m_edges; }

private:
  // Helper for recursion
  void collectTransitive(const std::string &node,
                         std::unordered_set<std::string> &visited,
                         std::vector<std::string> &out_libs);

  const QualifiedTarget *
  FindByQualifiedName(const std::string &qualified_name) const;

  enum class NodeState { Unvisited, Visiting, Done };

  log::Logger m_logger;

  // Reference copy tracking execution runtime configurations passed from CLI
  // parser loops
  const GlobalOptions &m_options;

  std::vector<QualifiedTarget>
  flattenManifestTree(std::shared_ptr<mokai::ProjectManifest> manifest,
                      const std::string &path_prefix);

  /**
   * @brief Builds the full set of dependency edges across every target in
   * m_allTargets, by resolving each target's raw `depends_on` entries via
   * resolveDependsOnEntry(). This must run after m_allTargets has been
   * populated (i.e. after flattenManifestTree()), since edge resolution looks
   * up other targets by qualified name within that same flat list.
   * @return One GraphEdge per resolved {from, to} pair.
   */
  std::vector<GraphEdge> buildEdges();

  /**
   * @brief Resolves a single raw `depends_on` string into zero or more real,
   * fully-qualified target names already present in m_allTargets.
   *
   * Supports four forms, checked in this order:
   * 1. "package:target"  -- explicit, bypasses defaults/profiles entirely.
   * 2. "package/profile" -- selects one of that package's [exports.profile.*].
   * 3. "name"             -- bare name, resolved as a SIBLING target first
   * (same owning_manifest as `from_target`).
   * 4. "name"             -- if no sibling matched, falls back to treating
   * it as a dependency name and uses that
   * dependency's exports.default_targets.
   *
   * Any resolution failure (unknown package, unknown target, missing
   * [exports], etc.) is logged via m_logger and simply omitted from the
   * returned list rather than throwing -- callers should expect a possibly
   * empty result on error.
   *
   * @param raw_dep      The raw string as written in a target's depends_on.
   * @param from_target  The QualifiedTarget that declared this dependency;
   * used to find its own manifest for sibling/package lookups.
   * @return A list of fully-qualified target names this entry resolves to.
   */
  std::vector<std::string>
  resolveDependsOnEntry(const std::string &raw_dep,
                        const QualifiedTarget &from_target);

  // Resolves raw token lines (literals, globs, and groups) into an explicit
  // vector of existing files
  std::vector<std::string>
  resolveTargetSources(const Target &target,
                       const std::shared_ptr<ProjectManifest> &manifest);

  void matchGlobPattern(const std::string &pattern, const std::string &base_dir,
                        std::vector<std::string> &matches);

  // Internal helper to expand brace notation tokens: "a{b,c}d" -> ["abd",
  // "acd"]
  std::vector<std::string> expandBraceNotation(const std::string &pattern);

  std::shared_ptr<ProjectManifest> m_root_manifest;
  std::vector<QualifiedTarget> m_allTargets;
  std::vector<GraphEdge> m_edges;
};

} // namespace mokai
