#include "config.hpp"
#include "cli/cli.hpp"
#include "config/tom.hpp"
#include "graph/types.hpp"
#include "log/log.h"
#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <expected>
#include <filesystem>
#include <format>
#include <fstream>
#include <iostream>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

#if !defined(_WIN32) && !defined(_WIN64)
#include <sys/wait.h>
#endif

namespace fs = std::filesystem;

namespace mokai {

static size_t calculateDistance(std::string_view s1, std::string_view s2) {
  const size_t len1 = s1.size(), len2 = s2.size();
  std::vector<std::vector<size_t>> d(len1 + 1, std::vector<size_t>(len2 + 1));
  for (size_t i = 0; i <= len1; ++i) {
    d[i][0] = i;
  }
  for (size_t j = 0; j <= len2; ++j) {
    d[0][j] = j;
  }

  for (size_t i = 1; i <= len1; ++i) {
    for (size_t j = 1; j <= len2; ++j) {
      size_t cost =
          (std::tolower(s1[i - 1]) == std::tolower(s2[j - 1])) ? 0 : 1;
      d[i][j] =
          std::min({d[i - 1][j] + 1, d[i][j - 1] + 1, d[i - 1][j - 1] + cost});
    }
  }
  return d[len1][len2];
}

static fs::path getGlobalMokaiDir() {
#if defined(_WIN32) || defined(_WIN64)
  const char *localAppdata = std::getenv("LOCALAPPDATA");
  return fs::path(localAppdata ? localAppdata : "C:\\") / "mokai";
#else
  const char *home = std::getenv("HOME");
  return fs::path(home ? home : "/tmp") / ".mokai";
#endif
}

Config::Config(std::string workingDir, GlobalOptions &ops) {
  if (!checkIsFolderAndExists(workingDir)) {
    std::string hint = "Ensure the specified project root path is correct.";
    auto fuzzyDir = fuzzyFindCloseFolder(workingDir);
    if (fuzzyDir.found) {
      hint = std::format("Did you mean to use directory '{}'?",
                         fs::path(fuzzyDir.best_match).filename().string());
    }
    Log::Error(std::format(
        "Specified directory does not exist or is inaccessible: '{}'\nHint: {}",
        workingDir, hint));
    return;
  }

  m_manifest.base_dir = workingDir;

  fs::path config_path = fs::path(workingDir) / "mokai.toml";
  std::string config_path_str = config_path.string();

  if (!checkIsFileAndExists(config_path_str)) {
    std::string hint = "Run 'mokai create' to scaffold a new workspace.";
    auto fuzzyFile = fuzzyFindCloseFile(config_path_str);
    if (fuzzyFile.found) {
      hint = std::format("A similar file exists: '{}'. Check if the file is "
                         "correctly named 'mokai.toml'.",
                         fs::path(fuzzyFile.best_match).filename().string());
    }
    Log::Error(
        std::format("Missing project manifest file at location: '{}'\nHint: {}",
                    config_path.string(), hint));
    return;
  }

  if (auto res = loadConfig(config_path_str); !res) {
    Log::Error(res.error());
    return;
  }

  if (auto res = parseConfig(); !res) {
    if (!res.error().empty()) {
      Log::Error(res.error());
    }
    return;
  }
  if (auto res = extractProjectData(ops); !res) {
    Log::Error("Failed to build project model from 'mokai.toml'.");
    Log::Error(res.error());
    return;
  }
}

std::expected<void, std::string> Config::loadConfig(const std::string &path) {
  std::ifstream file(path);
  if (!file.is_open()) {
    return std::unexpected(
        std::format("Unable to open manifest file: '{}'", path));
  }

  std::stringstream stream;
  stream << file.rdbuf();
  m_file_content = stream.str();

  if (m_file_content.empty()) {
    return std::unexpected(std::format(
        "Manifest file contains no configuration data: '{}'", path));
  }
  return {};
}

std::expected<void, std::string> Config::parseConfig() {
  // Use your streamlined flat parser instead of external library logic
  m_parser.parse(m_file_content);
  return {};
}

std::expected<void, std::string>
Config::extractProjectData(GlobalOptions &ops) {
  ProjectMetadata metadata;
  bool has_project_header = false;

  // Track uniquely indexed vectors/maps inside structures to assemble object
  // groupings dynamically
  struct TargetBuildState {
    std::string name;
    Target tgt;
  };
  struct HookBuildState {
    std::string name;
    Hook h;
  };
  std::vector<TargetBuildState> raw_targets;
  std::vector<HookBuildState> raw_hooks;

  // Loop through fields generated by your custom parser
  for (const auto &field : m_parser.fields) {
    // 1. Root [project] parsing logic
    if (field.scope == "project") {
      has_project_header = true;
      if (field.key == "name")
        metadata.name = field.value;
      else if (field.key == "version")
        metadata.version = field.value;
      else if (field.key == "license")
        metadata.license = field.value;
      else if (field.key == "description")
        metadata.description = field.value;
      else if (field.key == "homepage")
        metadata.homepage = field.value;
      else if (field.key == "default_target")
        metadata.default_target = field.value;
      else if (field.key == "default_compiler")
        ops.default_compiler = field.value;
      else if (field.key == "cpp_version")
        metadata.cpp_version = field.value;
      else if (field.key == "c_version")
        metadata.c_version = field.value;
      else if (field.key == "authors")
        metadata.authors.push_back(field.value);
      else if (field.key == "include_dirs")
        metadata.include_dirs.push_back(field.value);
      else if (field.key == "dependencies") {
        std::string depStr = field.value;
        metadata.dependencies.push_back(depStr);

        if (isLocDep(depStr)) {
          fs::path dep_path = fs::path(m_manifest.base_dir) / depStr;
          Log::Info(
              std::format("Resolving local path dependency: '{}'", depStr));

          if (!fs::exists(dep_path)) {
            return std::unexpected(
                std::format("Local dependency directory not found: '{}'",
                            dep_path.string()));
          }

          fs::path canonical_path = fs::canonical(dep_path);
          Config depconfig(canonical_path.string(), ops);
          DependencySpec spec{depStr, ""};
          m_manifest.resolved_dependencies[depStr] = ResolvedDependency{
              spec, std::make_shared<ProjectManifest>(depconfig.getManifest())};
        } else if (isGitDep(depStr)) {
          return std::unexpected(
              "Direct 'git:' dependency URLs are no longer supported. Please "
              "register and refer to packages using the global registry.");
        } else {
          std::string pkgName = depStr;
          std::string pkgVersionSpec = "latest";
          size_t versionDelim = depStr.find('@');
          if (versionDelim != std::string::npos) {
            pkgName = depStr.substr(0, versionDelim);
            pkgVersionSpec = depStr.substr(versionDelim + 1);
          }

          fs::path globalMokai = getGlobalMokaiDir();
          fs::path registryDir = globalMokai / "registry";

          if (!fs::exists(registryDir)) {
            Log::Info("Initializing global registry clone...");
            fs::create_directories(registryDir.parent_path());
            std::string regCloneCmd =
                "git clone --depth=1 --progress "
                "https://github.com/L1TerminalFault/mokai_confs " +
                registryDir.string();
            if (std::system(regCloneCmd.c_str()) != 0) {
              return std::unexpected(
                  "Critical failure while downloading dependencies metadata "
                  "maps from remote repository.");
            }
          }

          fs::path manifestRecipeFile = registryDir / (pkgName + ".toml");

          if (!fs::exists(manifestRecipeFile)) {
            Log::Info(std::format(
                "Package '{}' not found in local cache. Synchronizing index...",
                pkgName));
            std::string regCleanCmd = "git -C " + registryDir.string() +
                                      " reset --hard HEAD > /dev/null 2>&1";
            std::system(regCleanCmd.c_str());

            std::string regPullCmd =
                "git -C " + registryDir.string() + " pull --rebase --progress";
            std::system(regPullCmd.c_str());
          }

          if (fs::exists(manifestRecipeFile)) {
            std::ifstream rFile(manifestRecipeFile.string());
            std::stringstream rStream;
            rStream << rFile.rdbuf();

            try {
              tom::Parser recipeParser;
              recipeParser.parse(rStream.str());

              std::string gitRepo =
                  std::string(recipeParser.find_value("project", "git_repo"));
              if (gitRepo.empty()) {
                return std::unexpected(
                    std::format("Registry manifest for '{}' is missing "
                                "required 'git_repo' mapping.",
                                pkgName));
              }

              std::string packageGitUrl = gitRepo;
              if (!packageGitUrl.starts_with("http")) {
                packageGitUrl = "https://github.com/" + packageGitUrl;
              }

              std::string recipeTomlContent = std::string(
                  recipeParser.find_value("recipes", pkgVersionSpec));
              if (recipeTomlContent.empty()) {
                recipeTomlContent =
                    std::string(recipeParser.find_value("recipes", "latest"));
                if (!recipeTomlContent.empty()) {
                  Log::Warn(std::format("Version '{}' not found for '{}'. "
                                        "Falling back to 'latest'.",
                                        pkgVersionSpec, pkgName));
                }
              }

              if (recipeTomlContent.empty()) {
                return std::unexpected(std::format(
                    "Unable to resolve a valid build recipe for package '{}'.",
                    pkgName));
              }

              fs::path targetPkgBuildDir = globalMokai / "packages" / pkgName;
              fs::create_directories(targetPkgBuildDir.parent_path());

              if (!fs::exists(targetPkgBuildDir)) {
                Log::Info(std::format("Cloning global repository for '{}': {}",
                                      pkgName, packageGitUrl));
                std::string pkgCloneCmd = "git clone --progress " +
                                          packageGitUrl + " " +
                                          targetPkgBuildDir.string();
                if (std::system(pkgCloneCmd.c_str()) != 0) {
                  return std::unexpected(std::format(
                      "Git clone operation failed for package '{}'.", pkgName));
                }
              }

              fs::path destinationConfTarget = targetPkgBuildDir / "mokai.toml";
              std::ofstream outToml(destinationConfTarget.string());
              outToml << recipeTomlContent;
              outToml.close();

              Config depconfig(targetPkgBuildDir.string(), ops);
              DependencySpec spec{depStr, pkgVersionSpec};
              m_manifest.resolved_dependencies[pkgName] = ResolvedDependency{
                  spec,
                  std::make_shared<ProjectManifest>(depconfig.getManifest())};

            } catch (const std::exception &e) {
              return std::unexpected(std::format(
                  "Registry metadata parsing failure: {}", e.what()));
            }
          } else {
            return std::unexpected(
                std::format("Package '{}' is not registered in the central "
                            "package registry.",
                            pkgName));
          }
        }
      }
    }
    // 2. [project.version_from] inline parser map
    else if (field.scope == "project.version_from") {
      if (field.key == "file")
        metadata.version_from->file = field.value;
      else if (field.key == "pattern")
        metadata.version_from->pattern = field.value;
    }
    // 3. [options] block flag processing
    else if (field.scope == "options") {
      m_manifest.options[field.key] = (field.value == "true");
    }
    // 4. [compatibility] setup checks
    else if (field.scope == "compatibility") {
      if (field.key == "min_cpp_version")
        m_manifest.compatibility->min_cpp_version = field.value;
      else if (field.key == "preferred_cpp_version")
        m_manifest.compatibility->preferred_cpp_version = field.value;
    } else if (field.scope == "compatibility.unsupported_cpp_versions") {
      m_manifest.compatibility->unsupported_cpp_versions.push_back(field.value);
    } else if (field.scope == "compatibility.compilers.supported") {
      m_manifest.compatibility->compilers.supported.push_back(field.value);
    } else if (field.scope == "compatibility.compilers.unsupported") {
      m_manifest.compatibility->compilers.unsupported.push_back(field.value);
    }
    // 5. Array Tables for file rules, property macros, and compilation flags
    else if (field.scope.starts_with("group[")) {
      size_t idx = std::stoul(field.scope.substr(6, field.scope.find(']') - 6));
      if (m_manifest.file_groups.size() <= idx)
        m_manifest.file_groups.resize(idx + 1);
      if (field.key == "name")
        m_manifest.file_groups[idx].name = field.value;
      else if (field.key == "patterns")
        m_manifest.file_groups[idx].patterns.push_back(field.value);
    } else if (field.scope.starts_with("block[")) {
      size_t idx = std::stoul(field.scope.substr(6, field.scope.find(']') - 6));
      if (m_manifest.property_groups.size() <= idx)
        m_manifest.property_groups.resize(idx + 1);
      if (field.key == "name")
        m_manifest.property_groups[idx].name = field.value;
      else if (field.key == "condition")
        m_manifest.property_groups[idx].condition = field.value;
      else if (field.key == "defines")
        m_manifest.property_groups[idx].defines.push_back(field.value);
    } else if (field.scope.starts_with("hook[")) {
      size_t idx = std::stoul(field.scope.substr(5, field.scope.find(']') - 5));
      if (m_manifest.hooks.size() <= idx)
        m_manifest.hooks.resize(idx + 1);
      if (field.key == "name")
        m_manifest.hooks[idx].name = field.value;
      else if (field.key == "run")
        m_manifest.hooks[idx].run = field.value;
      else if (field.key == "target")
        m_manifest.hooks[idx].target = field.value;
      else if (field.key == "pattern")
        m_manifest.hooks[idx].pattern = field.value;
      else if (field.key == "on") {
        if (field.value == "pre_build")
          m_manifest.hooks[idx].trigger = HookTrigger::PreBuild;
        else if (field.value == "post_build")
          m_manifest.hooks[idx].trigger = HookTrigger::PostBuild;
        else if (field.value == "pre_target_build")
          m_manifest.hooks[idx].trigger = HookTrigger::PreTargetBuild;
        else if (field.value == "post_target_build")
          m_manifest.hooks[idx].trigger = HookTrigger::PostTargetBuild;
        else if (field.value == "file_change")
          m_manifest.hooks[idx].trigger = HookTrigger::FileChange;
      }
    }
    // 6. Dynamic uniquely-named [target.<name>] structure blocks
    else if (field.scope.starts_with("target.")) {
      std::string_view sub = std::string_view(field.scope).substr(7);
      size_t dot_pos = sub.find('.');
      std::string t_name = std::string(
          dot_pos == std::string_view::npos ? sub : sub.substr(0, dot_pos));

      auto it = std::find_if(raw_targets.begin(), raw_targets.end(),
                             [&](const auto &t) { return t.name == t_name; });
      if (it == raw_targets.end()) {
        Target new_tgt;
        new_tgt.name = t_name;
        raw_targets.push_back({t_name, new_tgt});
        it = std::prev(raw_targets.end());
      }

      if (dot_pos == std::string_view::npos) {
        if (field.key == "type") {
          if (field.value == "executable")
            it->tgt.type = TargetType::Executable;
          else if (field.value == "static_library")
            it->tgt.type = TargetType::StaticLibrary;
          else if (field.value == "shared_library")
            it->tgt.type = TargetType::SharedLibrary;
        } else if (field.key == "sources")
          it->tgt.sources.push_back(field.value);
        else if (field.key == "include_dirs")
          it->tgt.include_dirs.push_back(field.value);
        else if (field.key == "properties")
          it->tgt.properties.push_back(field.value);
        else if (field.key == "flags")
          it->tgt.flags.push_back(field.value);
        else if (field.key == "system_libs")
          it->tgt.system_libs.push_back(field.value);
        else if (field.key == "depends_on")
          it->tgt.depends_on.push_back(field.value);
      }
    }
    // 7. [exports] dynamic library layout data
    else if (field.scope == "exports") {
      // Ensure the optional is initialized before writing to any fields
      if (!m_manifest.exports.has_value()) {
        m_manifest.exports = mokai::Exports{};
      }

      if (field.key == "default_targets")
        m_manifest.exports->default_targets.push_back(field.value);
      else if (field.key == "include_dirs")
        m_manifest.exports->include_dirs.push_back(field.value);
      else if (field.key == "defines_required")
        m_manifest.exports->defines_required.push_back(field.value);
      else if (field.key == "defines_optional")
        m_manifest.exports->defines_optional.push_back(field.value);

    } else if (field.scope.starts_with("exports.profile.")) {
      // Ensure the optional is initialized here as well
      if (!m_manifest.exports.has_value()) {
        m_manifest.exports = mokai::Exports{};
      }

      std::string prof_name = field.scope.substr(16);
      m_manifest.exports->profiles[prof_name].targets.push_back(field.value);
    }
    // 8. Output configurations
    else if (field.scope == "output") {
      if (field.key == "directory")
        m_manifest.output.directory = field.value;
    } else if (field.scope.starts_with("output.configs.")) {
      std::string cfg_name = field.scope.substr(15);
      if (field.key == "enabled")
        m_manifest.output.configs[cfg_name].enabled = (field.value == "true");
      else if (field.key == "subdir")
        m_manifest.output.configs[cfg_name].subdir = field.value;
    }
  }

  if (!has_project_header) {
    return std::unexpected(
        "Missing required [project] header inside the configuration file.");
  }
  if (metadata.name.empty()) {
    return std::unexpected("Required field 'name' is missing or empty from the "
                           "[project] configuration.");
  }

  // Validate standards strings are matching standard options sets
  static const std::vector<std::string> known_versions{
      "c++11", "c++14", "c++17", "c++20", "c++23", "c++26"};
  if (metadata.cpp_version.empty())
    metadata.cpp_version = "c++23";
  if (!std::ranges::contains(known_versions, metadata.cpp_version)) {
    return std::unexpected(std::format("Unsupported C++ standard version: '{}'",
                                       metadata.cpp_version));
  }

  static const std::vector<std::string> known_c_versions{"c89", "c90", "c99",
                                                         "c11", "c17", "c23"};
  if (metadata.c_version.empty())
    metadata.c_version = "c11";
  if (!std::ranges::contains(known_c_versions, metadata.c_version)) {
    return std::unexpected(std::format("Unsupported C standard version: '{}'",
                                       metadata.c_version));
  }

  if (m_manifest.output.directory.empty()) {
    m_manifest.output.directory = "./build";
  }

  // Finalize targets vector validation
  for (auto &state : raw_targets) {
    m_manifest.targets.push_back(std::move(state.tgt));
  }

  m_manifest.project = std::move(metadata);
  return {};
}

bool Config::createProject(const std::string &projectName) {
  std::string chosenName = projectName;
  if (chosenName.empty()) {
    std::cout << "Enter project name [untitled_project]: ";
    std::getline(std::cin, chosenName);
    if (chosenName.empty()) {
      chosenName = "untitled_project";
    }
  }

  fs::path projectRoot = fs::current_path() / chosenName;
  if (fs::exists(projectRoot)) {
    Log::Error(
        std::format("Target directory '{}' already exists.", chosenName));
    return false;
  }

  try {
    fs::create_directories(projectRoot / "src");

    std::ofstream tomlFile(projectRoot / "mokai.toml");
    tomlFile << "[project]\n"
             << "name = \"" << chosenName << "\"\n"
             << "version = \"0.1.0\"\n"
             << "cpp_version = \"c++23\"\n\n"
             << "[target." << chosenName << "]\n"
             << "type = \"executable\"\n"
             << "sources = [\"src/main.cpp\"]\n";

    std::ofstream mainFile(projectRoot / "src" / "main.cpp");
    mainFile << "#include <iostream>\n\n"
             << "int main() {\n"
             << "    std::cout << \"Hello from " << chosenName << "!\\n\";\n"
             << "    return 0;\n"
             << "}\n";

    Log::Success(std::format("Scaffolded new project workspace at: {}",
                             projectRoot.string()));
    return true;
  } catch (const std::exception &e) {
    Log::Error(
        std::format("Failed to generate project skeleton: {}", e.what()));
    return false;
  }
}

bool Config::runTarget(const std::string &targetName) {
  const Target *matchedTarget = nullptr;
  for (const auto &t : m_manifest.targets) {
    if (t.name == targetName) {
      matchedTarget = &t;
      break;
    }
  }

  if (!matchedTarget) {
    std::string hint =
        "Verify target configurations defined in your mokai.toml.";
    std::string best_match;
    size_t min_dist = 4;
    for (const auto &t : m_manifest.targets) {
      size_t dist = calculateDistance(t.name, targetName);
      if (dist < min_dist) {
        min_dist = dist;
        best_match = t.name;
      }
    }
    if (!best_match.empty()) {
      hint = std::format("Did you mean target '{}'?", best_match);
    }

    Log::Error(
        std::format("Target '{}' not found.\nHint: {}", targetName, hint));
    return false;
  }

  if (matchedTarget->type != TargetType::Executable) {
    Log::Error(
        std::format("Target '{}' is not an executable type.", targetName));
    return false;
  }

  fs::path absoluteOutputBinPath =
      fs::path(m_manifest.base_dir) / m_manifest.output.directory;

  std::string profileSubdir = "";
  for (const auto &[key, profile] : m_manifest.output.configs) {
    if (profile.enabled) {
      profileSubdir = profile.subdir;
      break;
    }
  }
  if (!profileSubdir.empty()) {
    absoluteOutputBinPath /= profileSubdir;
  }
  absoluteOutputBinPath /= targetName;

  if (!fs::exists(absoluteOutputBinPath)) {
    Log::Error(std::format("Executable binary not found at: '{}'\nHint: Build "
                           "the target before executing it.",
                           absoluteOutputBinPath.string()));
    return false;
  }

  Log::Info(std::format("Executing target '{}' ({})", targetName,
                        absoluteOutputBinPath.string()));

  int exitStatus = std::system(absoluteOutputBinPath.string().c_str());

  if (exitStatus == -1) {
    Log::Error(std::format(
        "Process execution terminated with error on target: '{}'", targetName));
    return false;
  }

#if defined(_WIN32) || defined(_WIN64)
  return exitStatus == 0;
#else
  return WIFEXITED(exitStatus) && WEXITSTATUS(exitStatus) == 0;
#endif
}

bool Config::isGitDep(std::string &str) { return str.starts_with("git:"); }
bool Config::isLocDep(std::string &str) {
  return str.starts_with("./") || str.starts_with("../");
}
bool Config::checkIsFileAndExists(const std::string &path) {
  return fs::exists(path) && fs::is_regular_file(path);
}
bool Config::checkIsFolderAndExists(const std::string &path) {
  return fs::exists(path) && fs::is_directory(path);
}

FuzzyFindResult Config::fuzzyFindCloseFile(std::string &path) {
  fs::path p(path);
  fs::path parent = p.has_parent_path() ? p.parent_path() : fs::current_path();
  std::string filename = p.filename().string();

  if (!fs::exists(parent))
    return {false, ""};

  std::string best_match;
  size_t min_dist = 4;
  try {
    for (const auto &entry : fs::directory_iterator(parent)) {
      if (entry.is_regular_file()) {
        std::string entryName = entry.path().filename().string();
        size_t dist = calculateDistance(entryName, filename);
        if (dist < min_dist && dist > 0) {
          min_dist = dist;
          best_match = entry.path().string();
        }
      }
    }
  } catch (...) {
  }

  if (!best_match.empty())
    return {true, best_match};
  return {false, ""};
}

FuzzyFindResult Config::fuzzyFindCloseFolder(std::string &path) {
  fs::path p(path);
  fs::path parent = p.has_parent_path() ? p.parent_path() : fs::current_path();
  std::string folderName = p.filename().string();

  if (!fs::exists(parent))
    return {false, ""};

  std::string best_match;
  size_t min_dist = 4;
  try {
    for (const auto &entry : fs::directory_iterator(parent)) {
      if (entry.is_directory()) {
        std::string entryName = entry.path().filename().string();
        size_t dist = calculateDistance(entryName, folderName);
        if (dist < min_dist && dist > 0) {
          min_dist = dist;
          best_match = entry.path().string();
        }
      }
    }
  } catch (...) {
  }

  if (!best_match.empty())
    return {true, best_match};
  return {false, ""};
}

} // namespace mokai
